#!/bin/bash

curl --silent https://www.airnowapi.org/aq/observation/zipCode/current/\?format\=application/json\&zipCode\=94612\&distance\=3\&API_KEY\=$(cat ~/code/secrets/airnow_api_key) | jq '.[] | select(.ParameterName == "PM2.5") | .AQI'
