#!/bin/bash

editor_cmd=${FF_EDITOR_CMD:-nvim}
storage_file=${FF_STORAGE_FILE:-~/.focus_files}

usage() {
  cat << EOF
TODO write usage!
The current working directory is: $PWD
You are logged in as: $(whoami)
EOF
  exit 1
}

add_paths() {
  for p in "$@"
  do
    echo "$PWD/$p" >> "$storage_file"
  done
}

remove_paths() {
  for p in "$@"
  do
    # NOTE: this does not work with all `sed` distributions
    sed -i '' "/$p/d" "$storage_file"
  done
}

main() {
  if [ $# -eq 0 ]; then
    if [ -s "$storage_file" ]; then
      xargs "$editor_cmd" < "$storage_file"
    else
      $editor_cmd
    fi
    exit
  fi

  case $1 in
    set)
      # TODO when called with no additional args, shouldn't do anything
      shift
      echo "$PWD/$1" > "$storage_file"
      shift
      add_paths "$@"
      ;;
    add)
      shift
      add_paths "$@"
      ;;
    rm)
      shift
      remove_paths "$@"
      ;;
    view)
      shift
      cat "$storage_file"
      ;;
    edit)
      shift
      $editor_cmd "$storage_file"
      ;;
    help | *)
      usage
      ;;
  esac
}

main "$@"
