#!/bin/bash

# ripgrep fuzzy find in the current directory.
#
# adapted from https://github.com/junegunn/fzf/blob/master/ADVANCED.md#using-fzf-as-the-secondary-filter

# 1. Search for text in files using Ripgrep
# 2. Interactively narrow down the list using fzf
# 3. Open the file in nvim
IFS=: read -ra selected < <(
  rg --color=always --line-number --no-heading --smart-case "${*:-}" |
    fzf --ansi \
        --color "hl:9:underline,hl+:9:reverse" \
        --delimiter : \
        --preview 'bat --color=always {1} --highlight-line {2}'
)
[ -n "${selected[0]}" ] && nvim "${selected[0]}" "+${selected[1]}"
